#!/usr/bin/env perl

# !!! This is written specifically for MineColonies structure nbt files.
# !!! There are no checks for invalid data.
# !!! Use at your own peril!

# Use my version of Minecraft::NBTReader found at
# https://github.com/harleypig/Minecraft-NBTReader
#
# I've added support for the TAG_Int_Array type and removed a block for nbt
# files that end with two nulls.

# XXX: Do I need to include the location of the hut block in the output?
# XXX: Do I count 'double wooden slabs' as 2 slabs?

use strict;
use warnings;

#use Data::Dumper;
use File::Basename;
#use Minecraft::NBTReader;
#use YAML::Syck;
#
#$Data::Dumper::Indent=1;

use lib '.';
use MineColonies::Schematic::Load;
use MineColonies::Schematic::Parse;
use MineColonies::Schematic::Resources;

#################################################################################

my $filename = shift or die "Must pass filename.\n";
my $data     = MineColonies::Schematic::Load::read_file($filename);
my $hut_info = MineColonies::Schematic::Parse::parse_data($data);

MineColonies::Schematic::Resources::dump_required_resources( $hut_info, $filename );
